/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package registration;

import javax.swing.JOptionPane;

/**
 *
 * @author lab_services_student
 */
public class registration1 extends javax.swing.JFrame {

    /**
     * Creates new form registration1
     */
    public registration1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Username = new javax.swing.JLabel();
        Password = new javax.swing.JLabel();
        Firstname = new javax.swing.JLabel();
        Surname = new javax.swing.JLabel();
        Susername = new javax.swing.JTextField();
        Sfname = new javax.swing.JTextField();
        Ssurname = new javax.swing.JTextField();
        Spassword = new javax.swing.JPasswordField();
        Submit = new javax.swing.JButton();
        Clear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 0, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Registration form");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(188, 188, 188)
                .addComponent(jLabel1)
                .addContainerGap(483, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Username.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Username.setText("Username:");
        getContentPane().add(Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 83, 78, 42));

        Password.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Password.setText("Password:");
        getContentPane().add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 131, 78, 43));

        Firstname.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Firstname.setText("First name:");
        getContentPane().add(Firstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 180, 78, 45));

        Surname.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Surname.setText("Surname:");
        getContentPane().add(Surname, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 231, 78, 39));

        Susername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SusernameActionPerformed(evt);
            }
        });
        getContentPane().add(Susername, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 83, 276, 42));
        getContentPane().add(Sfname, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 180, 276, 45));
        getContentPane().add(Ssurname, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 231, 276, 39));
        getContentPane().add(Spassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 131, 276, 43));

        Submit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Submit.setText("Submit");
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });
        getContentPane().add(Submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 276, 132, 32));

        Clear.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Clear.setText("Clear");
        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearActionPerformed(evt);
            }
        });
        getContentPane().add(Clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 276, 126, 32));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SusernameActionPerformed

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
        // TODO add your handling code here:
        String Username= Susername.getText().toString();
        String Password= Spassword.getText().toString();
        String Firstname= Sfname.getText().toString();
        String Surname= Ssurname.getText().toString();
        if(Username.equals("")){
            JOptionPane.showMessageDialog(null,"Username is invalid");
        }
         if(Password.equals("")){
            JOptionPane.showMessageDialog(null,"Password is invalid");
        }
          if(Firstname.equals("")){
            JOptionPane.showMessageDialog(null,"Firstname is invalid");
        }
          if(Surname.equals("")){
            JOptionPane.showMessageDialog(null,"Surname is invalid");
        }
          else{
           JOptionPane.showMessageDialog(null,"validation success");
          }
    }//GEN-LAST:event_SubmitActionPerformed

    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearActionPerformed
        // TODO add your handling code here:
        Susername.setText(null);
        Spassword.setText(null);
        Sfname.setText(null);
        Ssurname.setText(null);     
    }//GEN-LAST:event_ClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registration1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registration1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registration1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registration1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registration1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Clear;
    private javax.swing.JLabel Firstname;
    private javax.swing.JLabel Password;
    private javax.swing.JTextField Sfname;
    private javax.swing.JPasswordField Spassword;
    private javax.swing.JTextField Ssurname;
    private javax.swing.JButton Submit;
    private javax.swing.JLabel Surname;
    private javax.swing.JTextField Susername;
    private javax.swing.JLabel Username;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
